name: queue TDD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v2 

      - name: Set up Python
        # Set up the Python environment
        uses: actions/setup-python@v2 
        with:
          # Specify the Python version
          python-version: '3.x' 

      - name: Install pipenv
        # Install pipenv
        run: pip install pipenv  

      - name: Install dependencies with pipenv
        # Install dependencies from Pipfile
        run: pipenv install --dev  

      - name: Run Tests with coverage
        run: |
          # Run pytest with coverage within the virtual environment
          pipenv run python3 -m pytest --verbose --cov=. --cov-report=xml --junit-xml=junit.xml 

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
