name: queue TDD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Set the Python version as per your project requirement

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov # if you need pytest-cov

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install pytest pytest-cov pytest_bdd
